/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class P11 extends javax.swing.JPanel {

    /**
     * Creates new form Histori_Pembelian
     */
    public P11() {
        initComponents();
        tampilkanpln();
    }
    private void tampilkanpln(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID_Transaksi");
        model.addColumn("Kode_Barang");
        model.addColumn("Tanggal");
        model.addColumn("Nama Pembeli");
        model.addColumn("Brand");
        model.addColumn("type");
        model.addColumn("Harga Beli");
        model.addColumn("Harga Jual");
        model.addColumn("Jumlah");
        model.addColumn("Total_Biaya");
        model.addColumn("Karyawan");
        

        try{
            int no = 1;
            String sql = "SELECT * FROM histori_penjualan";
            java.sql.Connection conn = (Connection)P13.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11)}); 
            }
             jTable3.setModel(model);            
        }catch (SQLException e){
            System.out.println("Error Koneksi : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Transaksi", "Kode Barang", "Tanggal", "Nama Pembeli", "Brand", "Type", "Harga_Beli", "Harga_Jual", "Jumlah", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        /*int baris = jTable3.rowAtPoint(evt.getPoint());
        String id = jTable3.getValueAt(baris, 0).toString();
        tf0.setText(id);

        String nomor = jTable3.getValueAt(baris, 1).toString();
        tf1.setText(nomor);

        String tgl = jTable3.getValueAt(baris, 2).toString();
        tf8.setText(tgl);

        String nama = jTable3.getValueAt(baris, 3).toString();
        tf7.setText(nama);

        String laptop = jTable3.getValueAt(baris, 4).toString();
        tf2.setText(laptop);

        String type = jTable3.getValueAt(baris, 5).toString();
        tf3.setText(type);

        String harga = jTable3.getValueAt(baris, 6).toString();
        tf4.setText(harga);

        String hargaj = jTable3.getValueAt(baris, 7).toString();
        tf5.setText(hargaj);

        String stok = jTable3.getValueAt(baris, 8).toString();
        tf10.setText(stok);

        String jml = jTable3.getValueAt(baris, 9).toString();
        tf9.setText(jml);*/
    }//GEN-LAST:event_jTable3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
